task :default => [:build, :install]

AGENT_NAME = "ZombieBuddy"
APP_ROOT   = File.expand_path("~/Library/Application Support/Steam/steamapps/common/ProjectZomboid/Project Zomboid.app")

task :build do
  sh "gradle build"
end

task :install do
  Dir["build/libs/*.jar"].each do |jar|
    puts "[.] installing #{jar}"
    FileUtils.cp jar, File.join(APP_ROOT, "Contents/Java/")
  end
end

task :clean do
  sh "gradle clean"
end
