task :default => [:build, :install]

AGENT_NAME = "ZombieBuddy"
APP_ROOT   = File.expand_path("~/Library/Application Support/Steam/steamapps/common/ProjectZomboid/Project Zomboid.app")

task :build do
  sh "gradle build"
end

task :install do
  Dir["build/libs/*.jar"].each do |jar|
    puts "[.] installing #{jar}"
    FileUtils.cp jar, File.join(APP_ROOT, "Contents/Java/")
  end
end

task :clean do
  sh "gradle clean"
end

desc "run the game"
task :run do
  sh "~/Zomboid/_steam/Contents/MacOS/JavaAppLauncher -javaagent:ZombieBuddy.jar --"
end

namespace :run do
  desc "debug the game"
  task :debug do
    sh "~/Zomboid/_steam/Contents/MacOS/JavaAppLauncher -javaagent:ZombieBuddy.jar=debug -- --debug -debug"
  end
end

desc "loop"
task :loop do
  loop do
    Rake::Task[:build].invoke
    Rake::Task[:install].invoke
    Rake::Task[:run].invoke
    puts
    puts "[press any key]"
    puts
    STDIN.getch
  end
end
