task :default => [:build, :install]

AGENT_NAME = "ZombieBuddy"
APP_ROOT   = File.expand_path("~/Library/Application Support/Steam/steamapps/common/ProjectZomboid/Project Zomboid.app")

task :build do
  env = {
    "JAVA_HOME" => "/Library/Java/JavaVirtualMachines/openjdk-24.jdk/Contents/Home"
  }
  sh env, "gradle build"
end

task :install do
  Dir["build/libs/*.jar"].each do |jar|
    puts "[.] installing #{jar}"
    FileUtils.cp jar, File.join(APP_ROOT, "Contents/Java/")
  end
end

task :clean do
  sh "gradle clean"
end

desc "run the game"
task :run, :verbosity, :exit_after_game_init, :debug do |t, args|
  cmd_args = []
  cmd_args << "verbosity=#{args.verbosity}" if args.verbosity
  cmd_args << "exit_after_game_init" if args.exit_after_game_init
  cmd_args_str = cmd_args.empty? ? "" : "=" + cmd_args.join(",")

  sh "~/Zomboid/_steam/Contents/MacOS/JavaAppLauncher -javaagent:ZombieBuddy.jar#{cmd_args_str} --"
end

namespace :run do
  desc "debug the game"
  task :debug do
    sh "~/Zomboid/_steam/Contents/MacOS/JavaAppLauncher -javaagent:ZombieBuddy.jar -- -debug"
  end
end

desc "build, install, and run"
task :iter => [:build, :install, :run]

desc "loop"
task :loop do
  loop do
    Rake::Task[:iter].invoke
    puts
    puts "[press any key]"
    puts
    STDIN.getch
  end
end
